basePath: /
host: localhost:8080
info:
  contact: {}
  description: HR management APi
  title: ClockOps API
  version: "1.0"
paths:
  /:
    get:
      consumes:
      - application/json
      description: testing if the server is running or not
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: First Route
      tags:
      - Health
swagger: "2.0"
